scripts/build.sh

Added entries into build.sh for Android dynamic and static versions.

[CTD-271] make Android builds

---

connectd/DEBIAN/control

Recommended by Dana.  https://semver.org/
Also incrementing patch number.  Note, the previous "patch" number (final digit) was 24, but we need the new version to be > than the previous version for lexical comparison.  So the patch number is now 4.

[CTD-269] move to semantic versioning. 

---

scripts/build.sh

[CTD-278] updated build script to make arm64 Debian package and

---

connectd/DEBIAN/control
connectd/usr/bin/connectd_library

Unit tested on Ubuntu.
Previous questions asking about protocol name and "is this a web connection or not" are gone.

[CTD-288] remove question to name custom protocol

---

connectd/DEBIAN/control
connectd/usr/bin/connectd_library

Tested with nginx running on Pi, set for https.

[CTD-287] added https option to interactive installer. 

---

connectd/DEBIAN/control
connectd/usr/bin/connectd_library

[CTD-296] made all "checkforXXX" into "checkForXXX" 

---

connectd/DEBIAN/control

[CTD-221] added dependency on lsb-base version 3.2

---

connectd/DEBIAN/control
scripts/build.sh

I have a few more commits on this expected but am opening the PR to run CI tests.

[CTD-114] removed PSFLAGS from build.sh; no longer used.

---

scripts/auto-install.sh

Used to reference the installer packages (build assets) at the same revision level for download.

[CTD-312] updated version in auto-install.sh.

---

connectd/DEBIAN/control

Increment minor version due to a couple feature editions.

[CTD-306] bumped version string to 2.3.x

---

connectd/DEBIAN/control
scripts/auto-install.sh

also added handling for the (unlikely?) case that no daemons work.

[CTD-316] add aarch64 support to auto install.sh

---

scripts/auto-install.sh
scripts/build.sh

Also added missing build targets to build.sh.

[CTD 334] auto install.sh fails on CentOS

---

connectd/usr/bin/connectd_installer
connectd/usr/bin/connectd_json
connectd/usr/bin/connectd_library
connectd/usr/bin/connectd_schannel
connectd/usr/bin/connectd_startup_control
connectd/usr/share/connectd/scripts/connectd_launch
connectd/usr/share/doc/connectd/copyright

(for the connectd_json module) to copyright file.

[CTD-233] made copyright statements consistent and added MIT License info

---

readme.md

Updated readme.md to match most recent release.

[CTD-154] Update readme.md

---

connectd/usr/bin/connectd_control

To be merged into Auto Reg epic branch

[RC-979] Added call to device ready API after provisioning

---

scripts/connectd_register

connectd_register is added to the scripts folder and will not be included in a build, were one to be made.
connectd_register is published and documented at forum.remote.it.  I am checking it in to put it under revision control.

CTD-403 checking in batch installer connectd_register.

---

scripts/extract-scripts.sh

of all files in tar packages to root:root.

CTD-407 change owner of all files in tar package to root:root

---

scripts/auto-install.sh

I also deleted a couple extraneous "echo" commands which are not important that the user see,

CTD-404-don't-run-tar-command-when-downloading-tar-file

---

connectd/usr/bin/connectd_library

people not to do so while using the connection in question.
A couple of white space changes crept into this one.

CTD-370 add warnings when deleting or adjusting services, to remind

---

connectd/DEBIAN/control
connectd/usr/bin/connectd_control
connectd/usr/bin/connectd_d2d
scripts/build.sh
test/Auto_Registration/auto-reg-test.sh
test/Interactive/interactive-test.sh

Changed re-entrant calls in connectd_control to function calls.

CTD-542 removed reentrant calls, changed to equivalent function calls

---

scripts/auto-install.sh

and also added a few more architectures that are now included with connectd 4.12.

CTD-614 updated version number and corrected the names of a few daemons
